# Compiler
CXX = clang++

# Compiler flags
CXXFLAGS = -Wall -std=c++17

# Output executable name
TARGET = zoo_game

# Source files
SRCS = main.cpp \
       Player.cpp \
       Tank.cpp \
       Zoo.cpp \
       LandEnclosure.cpp \
       Enclosure.cpp \
       Animal.cpp \
       Lion.cpp \
       LandAnimal.cpp \
       Information.cpp \
       AnimalInformation.cpp \
       EnclosureInformation.cpp \

# Header files
HDRS = Player.h \
       Tank.h \
       Zoo.h \
       LandEnclosure.h \
       Enclosure.h \
       Animal.h \
       game_logic.h \
       Lion.h \
       LandAnimal.h \
       AquaticAnimal.h \
       Dolphin.h \
       Information.h \
       AnimalInformation.h \
       EnclosureInformation.h \
       

# Object files (automatically generated by replacing .cpp with .o)
OBJS = $(SRCS:.cpp=.o)

# Default target
all: $(TARGET)

# Link object files to create the executable
$(TARGET): $(OBJS)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS)

# Compile .cpp files into .o files
%.o: %.cpp $(HDRS)
	$(CXX) $(CXXFLAGS) -c $<

# Clean up object files and the executable
clean:
	rm -f $(OBJS) $(TARGET)

# Phony targets
.PHONY: all clean
